language: python
cache: pip

python:
    - "3.6"

sudo: false

stages:
    - lint
    - test

matrix:

    fast_finish: true

    include:
        - { stage: lint, env: TOXENV=lint, }
        - { stage: lint, env: TOXENV=isort, }

        - { stage: test, env: TOXENV=unit, }
        - { stage: test, env: TOXENV=integration, }
        - { stage: test, env: TOXENV=functional, }

install:
    - pip install tox tox-travis

script:
    - tox

notifications:
    email: false
