language: python
cache: pip

python:
    - "3.6"

sudo: false

stages:
    - lint
    - test

matrix:

    fast_finish: true

    include:
        - { env: TOXENV=lint, stage: lint }
        - { env: TOXENV=isort, stage: lint }

        - { env: TOXENV=unit, stage: test }
        - { env: TOXENV=integration, stage: test }
        - { env: TOXENV=functional, stage: test }

install:
    - pip install tox tox-travis

script:
    - tox

notifications:
    email: false
